SOURCE = main.cpp DesTest.cpp ShowData.cpp\
	 RC2Test.cpp RSATest.cpp SSF33Test.cpp\
	 Des3Test.cpp RC4Test.cpp 
LIBS = -lepsng_p11
CFLAGS = -g
all:
	g++ $(CFLAGS) $(SOURCE) $(LIBS) -o pkcstest 
clean:
	rm -f pkcstest
